import type { AgentConfig, GlossaryEntry } from '../../../types';

export interface TranslationResult {
  raw: string;
  styled: string;
  metadata: {
    agentName: string;
    model: string;
    timestamp: string;
    glossaryMatches: string[];
    processingTime: number;
    inputLength: number;
    outputLength: number;
  };
}

export async function runMockTranslation(
  input: string, 
  agent: AgentConfig, 
  glossary: GlossaryEntry[]
): Promise<TranslationResult> {
  const startTime = Date.now();
  
  // Simulate processing delay
  await new Promise(resolve => setTimeout(resolve, 2000));
  
  let translatedText = input;
  const glossaryMatches: string[] = [];
  
  // Apply glossary replacements if glossary is provided
  if (glossary.length > 0) {
    glossary.forEach(entry => {
      const regex = new RegExp(`\\b${entry.term}\\b`, 'gi');
      if (regex.test(translatedText)) {
        translatedText = translatedText.replace(regex, entry.translation);
        glossaryMatches.push(`${entry.term} → ${entry.translation}`);
      }
    });
  }
  
  // Apply mock AI translations
  const mockTranslations: Record<string, string> = {
    'hello': 'hola',
    'world': 'mundo',
    'welcome': 'bienvenido',
    'please': 'por favor',
    'enter': 'ingrese',
    'username': 'nombre de usuario',
    'password': 'contraseña',
    'click': 'haga clic',
    'here': 'aquí',
    'continue': 'continuar',
    'save': 'guardar',
    'cancel': 'cancelar',
    'submit': 'enviar',
    'loading': 'cargando',
    'error': 'error',
    'success': 'éxito',
    'application': 'aplicación',
    'database': 'base de datos',
    'interface': 'interfaz',
    'button': 'botón',
    'form': 'formulario',
    'field': 'campo',
    'data': 'datos',
    'file': 'archivo',
    'folder': 'carpeta',
    'menu': 'menú',
    'window': 'ventana',
    'screen': 'pantalla',
    'page': 'página',
    'section': 'sección',
    'content': 'contenido',
    'text': 'texto',
    'image': 'imagen',
    'video': 'video',
    'audio': 'audio',
    'download': 'descargar',
    'upload': 'subir',
    'delete': 'eliminar',
    'edit': 'editar',
    'create': 'crear',
    'update': 'actualizar',
    'search': 'buscar',
    'find': 'encontrar',
    'filter': 'filtrar',
    'sort': 'ordenar',
    'view': 'ver',
    'show': 'mostrar',
    'hide': 'ocultar',
    'open': 'abrir',
    'close': 'cerrar',
    'start': 'iniciar',
    'stop': 'detener',
    'pause': 'pausar',
    'resume': 'reanudar',
    'back': 'atrás',
    'forward': 'adelante',
    'next': 'siguiente',
    'previous': 'anterior',
    'first': 'primero',
    'last': 'último',
    'all': 'todo',
    'none': 'ninguno',
    'some': 'algunos',
    'many': 'muchos',
    'few': 'pocos',
    'new': 'nuevo',
    'old': 'viejo',
    'big': 'grande',
    'small': 'pequeño',
    'high': 'alto',
    'low': 'bajo',
    'fast': 'rápido',
    'slow': 'lento',
    'good': 'bueno',
    'bad': 'malo',
    'yes': 'sí',
    'no': 'no',
    'ok': 'ok',
    'confirm': 'confirmar',
    'accept': 'aceptar',
    'reject': 'rechazar',
    'approve': 'aprobar',
    'deny': 'denegar',
    'allow': 'permitir',
    'block': 'bloquear',
    'enable': 'habilitar',
    'disable': 'deshabilitar',
    'activate': 'activar',
    'deactivate': 'desactivar',
    'connect': 'conectar',
    'disconnect': 'desconectar',
    'login': 'iniciar sesión',
    'logout': 'cerrar sesión',
    'register': 'registrarse',
    'signup': 'registrarse',
    'signin': 'iniciar sesión',
    'signout': 'cerrar sesión',
    'profile': 'perfil',
    'settings': 'configuración',
    'preferences': 'preferencias',
    'account': 'cuenta',
    'user': 'usuario',
    'admin': 'administrador',
    'guest': 'invitado',
    'member': 'miembro',
    'customer': 'cliente',
    'client': 'cliente',
    'server': 'servidor',
    'network': 'red',
    'internet': 'internet',
    'online': 'en línea',
    'offline': 'sin conexión',
    'connection': 'conexión',
    'link': 'enlace',
    'url': 'url',
    'website': 'sitio web',
    'webpage': 'página web',
    'homepage': 'página principal',
    'dashboard': 'panel de control',
    'overview': 'resumen',
    'summary': 'resumen',
    'details': 'detalles',
    'information': 'información',
    'help': 'ayuda',
    'support': 'soporte',
    'contact': 'contacto',
    'about': 'acerca de',
    'privacy': 'privacidad',
    'terms': 'términos',
    'conditions': 'condiciones',
    'policy': 'política',
    'license': 'licencia',
    'copyright': 'derechos de autor',
    'trademark': 'marca registrada',
    'version': 'versión',
    'release': 'lanzamiento',
    'upgrade': 'actualización',
    'backup': 'respaldo',
    'restore': 'restaurar',
    'export': 'exportar',
    'import': 'importar',
    'sync': 'sincronizar',
    'share': 'compartir',
    'send': 'enviar',
    'receive': 'recibir',
    'copy': 'copiar',
    'paste': 'pegar',
    'cut': 'cortar',
    'duplicate': 'duplicar',
    'clone': 'clonar',
    'move': 'mover',
    'rename': 'renombrar',
    'select': 'seleccionar',
    'choose': 'elegir',
    'pick': 'elegir',
    'option': 'opción',
    'choice': 'elección',
    'decision': 'decisión',
    'action': 'acción',
    'task': 'tarea',
    'job': 'trabajo',
    'project': 'proyecto',
    'work': 'trabajo',
    'time': 'tiempo',
    'date': 'fecha',
    'day': 'día',
    'month': 'mes',
    'year': 'año',
    'hour': 'hora',
    'minute': 'minuto',
    'second': 'segundo',
    'today': 'hoy',
    'yesterday': 'ayer',
    'tomorrow': 'mañana',
    'now': 'ahora',
    'later': 'más tarde',
    'soon': 'pronto',
    'never': 'nunca',
    'always': 'siempre',
    'sometimes': 'a veces',
    'often': 'a menudo',
    'rarely': 'raramente',
    'usually': 'usualmente',
    'normally': 'normalmente',
    'typically': 'típicamente',
    'generally': 'generalmente',
    'specifically': 'específicamente',
    'especially': 'especialmente',
    'particularly': 'particularmente',
    'mainly': 'principalmente',
    'mostly': 'mayormente',
    'largely': 'en gran parte',
    'entirely': 'completamente',
    'totally': 'totalmente',
    'fully': 'completamente',
    'partially': 'parcialmente',
    'slightly': 'ligeramente',
    'barely': 'apenas',
    'hardly': 'apenas',
    'almost': 'casi',
    'nearly': 'casi',
    'around': 'alrededor de',
    'roughly': 'aproximadamente',
    'exactly': 'exactamente',
    'precisely': 'precisamente',
    'accurately': 'con precisión',
    'correctly': 'correctamente',
    'properly': 'correctamente',
    'appropriately': 'apropiadamente',
    'suitably': 'adecuadamente',
    'adequately': 'adecuadamente',
    'sufficiently': 'suficientemente',
    'enough': 'suficiente',
    'too': 'demasiado',
    'very': 'muy',
    'quite': 'bastante',
    'rather': 'bastante',
    'fairly': 'bastante',
    'relatively': 'relativamente',
    'comparatively': 'comparativamente',
    'similarly': 'similarmente',
    'likewise': 'igualmente',
    'also': 'también',
    'as well': 'también',
    'in addition': 'además',
    'furthermore': 'además',
    'moreover': 'además',
    'besides': 'además',
    'however': 'sin embargo',
    'nevertheless': 'sin embargo',
    'nonetheless': 'sin embargo',
    'still': 'aún',
    'yet': 'aún',
    'though': 'aunque',
    'although': 'aunque',
    'despite': 'a pesar de',
    'in spite of': 'a pesar de',
    'regardless': 'sin importar',
    'anyway': 'de todos modos',
    'anyhow': 'de todos modos',
    'therefore': 'por lo tanto',
    'thus': 'por lo tanto',
    'hence': 'por lo tanto',
    'consequently': 'por consiguiente',
    'as a result': 'como resultado',
    'because': 'porque',
    'since': 'ya que',
    'as': 'como',
    'for': 'para',
    'to': 'a',
    'from': 'de',
    'with': 'con',
    'without': 'sin',
    'by': 'por',
    'through': 'a través de',
    'during': 'durante',
    'before': 'antes de',
    'after': 'después de',
    'until': 'hasta',
    'while': 'mientras',
    'when': 'cuando',
    'where': 'dónde',
    'why': 'por qué',
    'how': 'cómo',
    'what': 'qué',
    'which': 'cuál',
    'who': 'quién',
    'whom': 'a quién',
    'whose': 'cuyo',
    'this': 'este',
    'that': 'ese',
    'these': 'estos',
    'those': 'esos',
    'there': 'allí',
    'nowhere': 'en ninguna parte',
    'everywhere': 'en todas partes',
    'somewhere': 'en algún lugar',
    'anywhere': 'en cualquier lugar',
    'inside': 'dentro',
    'outside': 'fuera',
    'above': 'arriba',
    'below': 'abajo',
    'under': 'debajo',
    'over': 'sobre',
    'between': 'entre',
    'among': 'entre',
    'across': 'a través',
    'along': 'a lo largo',
    'beside': 'al lado',
    'next to': 'al lado',
    'near': 'cerca',
    'far': 'lejos',
    'close': 'cerca',
    'distant': 'distante',
    'local': 'local',
    'global': 'global',
    'international': 'internacional',
    'national': 'nacional',
    'regional': 'regional',
    'urban': 'urbano',
    'rural': 'rural',
    'domestic': 'doméstico',
    'native': 'nativo',
    'foreign': 'extranjero',
    'imported': 'importado',
    'exported': 'exportado',
    'manufactured': 'fabricado',
    'produced': 'producido',
    'created': 'creado',
    'made': 'hecho',
    'built': 'construido',
    'developed': 'desarrollado',
    'designed': 'diseñado',
    'planned': 'planificado',
    'organized': 'organizado',
    'arranged': 'organizado',
    'sorted': 'ordenado',
    'classified': 'clasificado',
    'categorized': 'categorizado',
    'grouped': 'agrupado',
    'divided': 'dividido',
    'split': 'dividido',
    'separated': 'separado',
    'combined': 'combinado',
    'merged': 'fusionado',
    'joined': 'unido',
    'connected': 'conectado',
    'linked': 'vinculado',
    'attached': 'adjunto',
    'detached': 'desconectado',
    'removed': 'eliminado',
    'deleted': 'eliminado',
    'erased': 'borrado',
    'cleared': 'limpiado',
    'emptied': 'vacío',
    'filled': 'lleno',
    'loaded': 'cargado',
    'unloaded': 'descargado',
    'started': 'iniciado',
    'stopped': 'detenido',
    'paused': 'pausado',
    'resumed': 'reanudado',
    'restarted': 'reiniciado',
    'reset': 'restablecido',
    'refreshed': 'actualizado',
    'reloaded': 'recargado',
    'reopened': 'reabierto',
    'recreated': 'recreado',
    'rebuilt': 'reconstruido',
    'redesigned': 'rediseñado',
    'reorganized': 'reorganizado',
    'rearranged': 'reorganizado',
    'resorted': 'reordenado',
    'reclassified': 'reclasificado',
    'recategorized': 'recategorizado',
    'regrouped': 'reagrupado',
    'redivided': 'redividido',
    'resplit': 'redividido',
    'reseparated': 'reseparado',
    'recombined': 'recombinado',
    'remerged': 'refusionado',
    'rejoined': 'reunido',
    'reconnected': 'reconectado',
    'relinked': 'revincular',
    'reattached': 'readjunto',
    'redetached': 'redesconectado',
    'reremoved': 'reeliminado',
    'redeleted': 'reeliminado',
    'reerased': 'reborrado',
    'recleared': 'relimpiado',
    'reemptied': 'revacío',
    'refilled': 'relleno',
    'reunloaded': 'redescargado'
  };
  
  // Apply mock translations (case-insensitive)
  Object.entries(mockTranslations).forEach(([source, target]) => {
    const regex = new RegExp(`\\b${source}\\b`, 'gi');
    translatedText = translatedText.replace(regex, target);
  });
  
  const processingTime = Date.now() - startTime;
  
  // Generate metadata
  const metadata = {
    agentName: agent.name,
    model: agent.model,
    timestamp: new Date().toISOString(),
    glossaryMatches,
    processingTime,
    inputLength: input.length,
    outputLength: translatedText.length
  };
  
  // Generate raw output (JSON format)
  const rawOutput = JSON.stringify({
    input,
    output: translatedText,
    agent: {
      name: agent.name,
      model: agent.model,
      prompt: agent.prompt
    },
    glossary: glossary.length > 0 ? {
      enabled: true,
      entries: glossary.length,
      matches: glossaryMatches
    } : {
      enabled: false
    },
    metadata
  }, null, 2);
  
  return {
    raw: rawOutput,
    styled: translatedText,
    metadata
  };
} 